Exercise 2
brickers/DevOps-Course-Starter pull request #2
Opened 2021-03-22 16:03 UTC by brickers

I have deviated from the requirements slightly: rather than hard code a button to move a card to 'Done', the app generates buttons to move the card to other lists. I thought this met the brief, was more useful as you can move to any list you like, and is works with however many lists the user has and whatever they are named. It also satisfied the second part of the brief, letting users move cards back the other way. In a prod environment I would probably create a dropdown menu to tidy up the UI, but haven't done that here.

2021-03-30 16:46 UTC, JackMead requested changes
This looks good, more than happy with your decision re the buttons to change lists, and I like the feature to search for different boards to start with!
I've left a few thoughts below, but the main thing we should adjust is that the class added for Part 5 (`Card` in your case) is a little confused, the idea here is to use the class when passed through to the templates, and it should know how to digest a trello response (as you have it) but it shouldn't need to make calls to trello within the class itself - I wouldn't expect to see that class required when creating a new card or moving a card between lists

Feel free to shout if that's not clear, (or indeed even if the motivation for it isn't!)

2021-03-30 16:46 UTC, JackMead commented on README.md
> +- In the .env file, add two lines under where it says `# Change the following values for local development.`, ensuring the correct copied values are included:
Nice clear instructions!
Minor - but relevant because of just how often people ignore instructions - it would be nice to also add these two keys to the `.env.template` file, in the hope that might catch some people who otherwise miss this part of the instructions

2021-03-30 16:46 UTC, JackMead commented on todo_app/app.py
> +if __name__ == '__main__':
If we're only ever running the app through `poetry run flask run`, we can actually get rid of this part now

2021-03-30 16:46 UTC, JackMead commented on todo_app/app.py
> +# i would prefer this to be a PATCH route as we are only changing one part of
Good point & sensible conclusion, more than happy for this to be POST for exactly this reason

2021-03-30 16:46 UTC, JackMead commented on todo_app/app.py
> +        if card.lastResponseOK:
This is slightly oddly structured - first you use the card id to get the card from trello, then you use the same card id to move it to a list; the first call to Trello only helps us by establishing the board id (but that's not particularly obvious)
Separately, separating the Card class (the info relating to a card) from the logic to move a card about would probably make sense here, e.g. we might make `moveToList` another function similar to `getListCards` etc, that makes the request, rather than asking the card class to manage that itself.

2021-03-30 16:46 UTC, JackMead commented on todo_app/app.py
> +            return redirect(f"/board/{card.getBoardID()}")
Worth noting that you have an if clause here but no alternative - this view will just error due to no return if the `lastResponseOk` is false

2021-03-30 16:46 UTC, JackMead commented on todo_app/app.py
> +        if len(args) > 1 and isinstance(args[0], str) and isinstance(args[1], str):
This is reasonably hard to follow, an alternative pattern would be to use a static factory method to split that out, e.g.
```

class Card:
    def __init__(self, name, idList, idCard = None, idBoard = None, ):
        self.name = name
        self.idList = idList
        if idCard == None or idBoard == None:
            url = BASE_URL + f"/1/cards"
            params = {
                "name": self.name,
                "idList": self.idList
            }
            response = requests.post(url, params=params, headers=auth_header)
            json =  response.json()
            self.idBoard = json['idBoard']
            self.id = json['id']
            self.lastResponseOK = response.ok
        else:
            self.id = idCard
            self.idBoard = idBoard

    @classmethod
    def from_trello_card(cls, trello_response):
        json = trello_response
        name = json["name"]
        id = json["id"]
        idList = json["idList"]
        idBoard = json["idBoard"]
        cls(name, id, idList, idBoard)
```

Saying that, we could certainly improve this further if we separated the Card class from the logic inside it that creates a card - we'd then only need a single constructor for now (since addCardToList wouldn't need to actually create a card)

2021-03-30 16:46 UTC, JackMead commented on todo_app/app.py
> +        return render_template("board.html", board=board)
Here we're passing through essentially the json directly from Trello  (albeit modified to combine some useful fields), rather than creating our own class to use in the templates

2021-04-16 09:42 UTC, brickers commented on todo_app/app.py
> +            return redirect(f"/board/{card.getBoardID()}")
Hi Jack. I'm not totally sure I considered this, and if I did then perhaps I assumed that because it's in a `try` block it would then be managed by the exception, but I see now that no error occurs so that probably wouldn't happen. I will update with an `else` leading to the error page.

2021-04-16 16:21 UTC, brickers commented on todo_app/app.py
> +        return render_template("board.html", board=board)
this has been changed now

2021-04-16 16:22 UTC, brickers commented on todo_app/app.py
> +        if len(args) > 1 and isinstance(args[0], str) and isinstance(args[1], str):
thanks for this. i think i was trying to do something I've done in other languages and really it wasn't clear. certainly i found it hard to read coming back to it! also good to see how the confusion over the purpose of Class caused this to be more complex than necessary

2021-04-16 16:23 UTC, brickers commented on todo_app/app.py
> +        if card.lastResponseOK:
sorted

2021-04-16 16:23 UTC, closed without merging