Exercise 3
brickers/DevOps-Course-Starter pull request #4
Opened 2021-05-20 20:30 UTC by brickers

2021-05-26 09:00 UTC, JackMead requested changes
Nice work, your tests are all good examples of the different levels of testing. I've left a few thoughts below on some things we could adjust, but in particular there are a couple of places where your tests rely on some non-obvious behaviour from VSCode in order to work so that e.g. they fail when run from a terminal, and we should resolve that.

2021-05-26 09:00 UTC, JackMead commented on .gitignore
> +.vscode/settings.json
You've already ignored this folder entirely in the line above so no harm but no need for this in addition

2021-05-26 09:00 UTC, JackMead commented on pyproject.toml
> +selenium = "^3.141.0"
We could also make this a dev-dependency

2021-05-26 09:00 UTC, JackMead commented on tests/test_ViewModel.py
> +    assert len(todo_items) == 2
I'd combine these tests; they're all individual asserts that together make up a test I'd call `test_board_get_todo_items_returns_todo_list` or similar - I'd expect these tests to generally work or break in tandem

2021-05-26 09:00 UTC, JackMead commented on tests/test_ViewModel.py
> +    assert todo_list_id == 7
Minor, but it would be nice to extract the id here into a constant - reading this test requires reading the setup to be confident it's testing the right thing

2021-05-26 09:00 UTC, JackMead commented on todo_app/app.py
>  from todo_app.flask_config import Config
You're no longer referencing this config directly, so we don't need this import any more, and in fact further it causes errors when the tests are run from the command line as it tries to read environment variables before your test has had a chance to set those

2021-05-26 09:00 UTC, JackMead commented on todo_app/api.py
> +    base_url = os.getenv('BASE_URL')
Similarly to the config; by setting this at a class level it executes _before_ your test has read in the `.env` / `.env.test` file - this means your tests error from the command line. VSCode may not show that behaviour, because it's silently loading in the .env file before running the test
One solution would be to adjust this to a static method that gets the base_url on the fly; this way it would only be evaluated when needed rather than at start up

2021-05-26 09:00 UTC, JackMead commented on todo_app/api.py
> +        pass
We can just leave out this constructor if it's not doing anything

2021-05-26 09:00 UTC, JackMead commented on todo_app/card.py
> +        self._id_list = id_list
Now that you've got properties we could take advantage of inbuilt setter behaviour:
```python
    @id_list.setter
    def set_id_board(self, id_board):
        self._id_board = id_board
```

This will then allow other modules to act as if they're updating the field directly:
```python
card.id_list = idList
```

2021-05-26 09:00 UTC, JackMead commented on todo_app/templates/list.njk
> +{% import "card.njk" as cardMacro %}
Is there a reason you've used the `.njk` file format?
This appears to be for a templating framework Nunjucks, but we're using Jinja2 by default and I can't see evidence of a switchover. Jinja clearly isn't worried about that, but by default we'd expect .html file endings

2021-05-26 09:00 UTC, JackMead commented on tests_e2e/test_e2e.py
> +API = api.API
This is essentially avoiding a specific import, such as `from todo_app.api import API`

2021-05-26 09:00 UTC, JackMead commented on tests_e2e/test_e2e.py
> +    board_name = os.environ['SELENIUM_BOARD_NAME']
Note that this depends on the environment variables being present, even though you've not explicitly asked for that - pytest doesn't load those in automatically, although to be confusing VSCode's test runner does. We should load in the `.env` file before this line in a similar way to how we loaded in `.env.test` in the integration test

2021-05-26 09:00 UTC, JackMead commented on .env.template
> +SELENIUM_BOARD_ID=0
Note that we don't care what the user sets this to in advance since the app will overwrite it, so we don't need to include it in this file. Similarly, the user doesn't need the SELENIUM_BOARD_NAME variable for running locally, so I'd be inclined to just pick a value and directly hardcode that into the test

2021-05-26 09:00 UTC, JackMead commented on tests_e2e/test_e2e.py
> +    time.sleep(10)
We can usually refactor to avoid sleeps, but occasionally they are the easiest workaround - I'm not sure why we'd need one here though?

2021-05-26 09:00 UTC, JackMead commented on tests_e2e/test_e2e.py
> +    time.sleep(5)
In this test, you've actually written it really cleanly to be able to avoid these sleeps by always looking for new elements and asserting on them. If you set the implicit wait time for the driver at the start of the test (or even when creating the driver in the fixture, with `driver.implicitly_wait(5)`) then it will allow up to (here) 5 seconds, without waiting the full 5 seconds if it can avoid it

2021-05-26 09:00 UTC, JackMead commented on README.md
> +## Testing
It would be worthwhile really clearly spelling out how these tests can be run, e.g. with `poetry run pytest`

2021-06-02 11:34 UTC, brickers commented on todo_app/card.py
> +        self._id_list = id_list
this is good to know, although I haven't implemented it because it started to cause an error which I don't feel I have time to look into right now.

2021-06-02 11:37 UTC, brickers commented on todo_app/templates/list.njk
> +{% import "card.njk" as cardMacro %}
pure confusion between this and a personal project I was working on!

2021-06-02 11:46 UTC, brickers commented on tests_e2e/test_e2e.py
> +    time.sleep(10)
I found that it took some time for the flask up to get up and running after being created, and selenium just runs through all commands as quickly as possible. The next action was to load the app in the browser via a URL, and without the sleep this would fail as 'unable to connect'. I also had spent a significant amount of time on this module and didn't have the time to investigate something more preferable.

2021-06-02 11:54 UTC, brickers commented
I have resolved the majority of the issues you raised, with only the question around the use of sleep in the `app_with_temp_board` fixture outstanding.

2021-06-15 16:29 UTC, JackMead approved these changes
Thanks for making those changes; there is one small issue that's blocking your end-to-end test for running for me, but I've left a note below on options for fixing that, and I'm happy for you to merge this without a re-review once you've adjusted for that.

2021-06-15 16:29 UTC, JackMead commented on tests_e2e/test_e2e.py
> +    SELENIUM_BOARD_ID = board_id
This change has broken your tests again for me I'm afraid! If you want to modify this variable within the function, you'll need to specify that explicitly with the `global` keyword - (see [Stack Overflow for an example](https://stackoverflow.com/questions/10588317/python-function-global-variables) or [an explanation](https://www.programiz.com/python-programming/global-keyword)) but I'd lean towards your solution of storing it in an environment variable here.
I.e. we could fix by switching back to the env variable, or by switching this line for:
```python
    global SELENIUM_BOARD_ID
    SELENIUM_BOARD_ID = board_id
```

2021-06-15 16:29 UTC, JackMead commented on tests_e2e/test_e2e.py
> +    time.sleep(10)
That should be accounted for with your approach below which will take advantage of the implicit wait; running locally I have no issues removing this line and executing it, but I'm happy for you to ignore this as a potential time sink!

2021-06-17 10:48 UTC, merged